### ISSUE TITLE
Please release targeting netstandard 2.0

### ISSUE THREAD

**Issue by gulshan** [reflectsoftware/reflectsoftware-facebook#1]
This is a great package. Please release targeting netstandard 2.0

**Comment by codematrix** [comment]
I'll take a look. I do use Facebook's nuget. So if they support it I can see why I wouldn't be able to support.
If you, fork the repo and create a PR and I'll review it and commit the changes.

**Comment by gulshan** [comment]
I do not have the windows .net setup. I am using mac with vscode and command line tools. I was most concerned with "ReflectSoftware.Facebook.Messenger.Common" package. The change I made is-
from
```xml
<TargetFramework>net461</TargetFramework>
```
to 
```xml
<TargetFramework>netstandard2.0</TargetFramework>
```
in the .csproj file. The build was successful. But I'm not sure if that will be working in your setup.

**Comment by codematrix** [comment]
OK let me look at it.  You can leave the <TargetFramework>net461</TargetFramework> and just add additional target frameworks like <TargetFramework>netstandard2.0</TargetFramework>.

I also want to see if the Facebook client library already supports as <TargetFramework>netstandard2.0</TargetFramework> as well. If so I can add support for <TargetFramework>netstandard2.0</TargetFramework>.

In addition, I want to see if it's possible to add text when uploading attachments. I need this for a project I'm currently work on. 

I'll keep you posted.

**Comment by codematrix** [comment]
@gulshan OK I added the additional targets for both the Webhook and Common libraries. They support  both >= netstandard2.0. and net461.

However, I had to keep the Client library as is. This is because it has a Facebook client that it depends on, which doesn't support netstardard2.0.  This library is mainly used to send messages.  At some point I can remove this library and send the messages directly using RestSharp.

You can now get the latest versions 2.1.2.

Let me know if you have any issues. I tested locally and it all works fine for me. 

Please close this issue if all is good.

**Comment by gulshan** [comment]
It's working. Thanks a lot!
